name = "teste"
uuid = "b8e31acb-4a4e-497c-a980-20dcba246b30"
authors = ["Brad Lindblad"]
version = "0.1.0"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
